### ISSUE TITLE
Handling of unrecognized capsule types

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-masque/draft-ietf-masque-h3-datagram#126]
With #124 and https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/pull/70, there is no longer a CLOSE_CONTEXT_ID Capsule, with its associated error codes.  H3 Datagram still says that unknown capsule types must be ignored.  This creates a dilemma: if I send a capsule like REGISTER_FOO_CONTEXT, acknowledged by a REGISTER_FOO_ACK response, how do I know if it worked?  If the REGISTER_FOO_CONTEXT capsule is ignored, I will have to wait indefinitely for the ACK, or set a timeout (yuck).

There are a few different ways to solve this, but I think the cleanest is the REGISTER_DATAGRAM_CONTEXT capsule type from the (published) H3 Datagram draft.  CONNECT-IP and CONNECT-UDP can make that capsule type mandatory to implement, so we don't need to worry about whether the other side supports it.

This also highlights why we need a "Datagram Contexts" draft supporting CONNECT-UDP and CONNECT-IP.  We need the "Datagram Format Types" concept, the CLOSE_DATAGRAM_CONTEXT capsule type, and all the other bits.  We could paste all of this into CONNECT-UDP, but I don't think we want to cross-reference it out of CONNECT-UDP every time we need to define a new extension or format.

**Comment by bemasc** [comment]
@tfpauly From yesterday's meeting I recall you were less interested in opening a new draft for Datagram Format Contexts.  How do you think we should resolve this problem?

**Comment by tfpauly** [comment]
@bemasc My suggestion is that CONNECT-UDP and CONNECT-IP both define that they use a varint as the first field in the datagram body, which is an identifier that capsules can register, and then various extensions define their own formats. Each new capsule/datagram extension would define its own Datagram Payload format.

I strongly feel that we shouldn't have a generic REGISTER_DATAGRAM_CONTEXT or CLOSE_DATAGRAM_CONTEXT, since then you just need another registry of types within that. The capsule registry itself is sufficient.

Each extension can define for itself the capsules it needs. Not all extensions need the ability to ack or close, but some do. So, if your extension needs to be have ACKs and CLOSE, define that. If you don't, don't.

You could have:
REGISTER_FOO_CONTEXT
ACK_FOO_CONTEXT
CLOSE_FOO_CONTEXT

And for some other extension:

REGISTER_BAR_CONTEXT
CLOSE_BAR_CONTEXT

And maybe for another, just a register:

REGISTER_XYZ_CONTEXT

**Comment by bemasc** [comment]
@tfpauly OK, so I send you a REGISTER_FOO_CONTEXT and then I wait for ACK_FOO_CONTEXT to confirm.  How long do I wait before concluding that you don't support FOO, and dropped the capsule as unrecognized?

**Comment by tfpauly** [comment]
You can use request headers that are expected to be echoed in responses to indicate if the other supports the extension at all.

Alternatively, there could be a generic "I didn't understand your capsule type" error. I think that's better than trying to generalize context-specific errors.

**Comment by DavidSchinazi** [comment]
HTTP headers are the best mechanism to establish support for extensions. I don't think we need anything generic here, we could revisit that if we see multiple extensions duplicating work though.

**Comment by bemasc** [comment]
I've drawn up an example ([see here](https://bemasc.github.io/h3-datagram-ping/bemasc-timestamp-designteam/draft-schwartz-masque-h3-datagram-ping.html)) of how I think PING and TIMESTAMP extensions would work in this model (no generic registration, support negotiated by headers).  It can be done!

In my view, the lack of any generic signaling for context creation is going to be a major pain for implementors, resulting in a lot of duplicated (or worse, almost-duplicated) code.  To streamline it, I've left out all the detailed error codes for malformed or excessive registrations, which would also have to be duplicated for each extension.

I think we'll get a higher-quality standard if context lifetime management is defined and implemented once, well, instead of being redefined and reimplemented poorly for each extension.
