### ISSUE TITLE
Add to security considerations that it's not possible to generate CONNECT from JS

### ISSUE THREAD

**Issue by ekr** [ietf-wg-masque/draft-ietf-masque-h3-datagram#128]
And point to https://fetch.spec.whatwg.org/#methods

This is an important part of the security analysis.

**Comment by martinthomson** [comment]
So this assumption is useful in that it helps us avoid an analysis.  Though my sense is that that analysis isn't especially difficult.  The header field exists to enable datagram forwarding behaviour in an intermediary.  We only have to show that there is no harm inflicted if a client engages that behaviour for requests, under the constraint that the client is otherwise authorized to make from a web context.  The risk comes if this forwarding behaviour somehow generates different semantics as a result.  As the same client also provides the stream of data that will be forwarded, it is trivial to see that they are already in a position to engage whatever semantics they choose.  The only scenario that might benefit an attacker is where the elision of datagrams (or things that look like them) might be used to evade security protections that scan the stream of data.  For an attack to be effective, those same protections would have to be ignorant of datagram forwarding behaviour at the same intermediary.

This binding to CONNECT is a useful shortcut that means we don't need to engage with all that stuff, which wouldn't be that easy to write down. (This aversion to engagement is, I believe, a large part of why people want to slap "Sec-" on all new headers.)

**Comment by LPardue** [comment]
MT's framing of this is helpful. 

Adding some security consideration about what might go wrong for an intermediary seems potentially useful. Spending text on why a browser is special in this regard seems less compelling to nme.

**Comment by DavidSchinazi** [comment]
I was about to write a PR for this, but I think we should first resolve #129. If we decide that capsules are only allowed for HTTP upgrade tokens (and not new methods) then we've restricted ourselves to CONNECT and Upgrade which are both inaccessible from JavaScript.
