### ISSUE TITLE
Interoperability for all HTTP Datagrams or defined by HTTP Extension

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#168]
I think the draft do need to decide if it defines HTTP Datagrams to be always interoperable or if it is up to the HTTP extension to define how one becomes interoperable. As seen in #165 the later school of though might have been leading, while not considering the attempt to be generic. If one will leave it to the HTTP Extension, then I think a section is needed to make it clear what an HTTP Extension needs to think about and define to be interoperable. 

I would think making the basics of HTTP Datagrams interoperable including when Intermediaries are doing re-encoding without knowing the upgrade token might be the simplest even if it will require Datagram Capsule to be supported by all HTTP Extensions.

**Comment by DavidSchinazi** [comment]
What do you mean by "interoperable" here?

**Comment by DavidSchinazi** [comment]
To add to my previous comment: I don't fully understand what this issue is about. HTTP Datagrams by themselves are interoperable but don't have semantics - they're a tool that HTTP extensions can use. The HTTP extensions interoperate between client and server implementation of such extension, and the intermediaries ferry bytes back and worth. Perhaps you could phrase this differently: what is the problem here? Is this document too vague such that it would be possible to write an HTTP extension that doesn't interoperate?

**Comment by gloinul** [comment]
Lets close this and take the discussion in #167
