### ISSUE TITLE
Flow Control and Capsule/Datagram

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-masque/draft-ietf-masque-h3-datagram#199]
This is a non-blocking comment from AD review. I have no concerns if the authors choose to close it with no action.

It might be worthwhile to discuss the interaction of stream flow control with capsule/datagram conversions. With other HTTP transactions, intermediaries can deliver whatever in-order bytes of the stream they have. When receiving capsules and emitting datagrams, if the stream flow control window is too small to accept the datagram size, there can be a deadlock. A sentence about this special case could avoid a silly implementer mistake.

**Comment by LPardue** [comment]
I think this goes beyond just intermediaries. Instead it applies to any consumer of capsules where they might be tempted to try and buffer the capsule, in the data stream, in its entirety before processing or consuming it. That might be obvious as a "bad thing" for implementers that are already used to handling H2 or H3 frames. However, you identify that the DATAGRAM capsule is particularly tempting to buffer because it should be handled atomically. 

So I think it might help to briefly point out some deadlock considerations about flow window sizes in relation to capsule sizes, and processing / release of further window credits.

**Comment by DavidSchinazi** [comment]
Adding a little bit of text to warn against such cases SGTM
