### ISSUE TITLE
Datagram Flow Id parameters should be not be names

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-h3-datagram#24]
Rather than having names like `44; ecn-ect0`, the parameters should follow the usual parameter format, which would be like:

44; ecn=ect0

**Comment by LPardue** [comment]
My understanding of the ask that lead to the "name parameter" being defined in draft-schinazi-masque-h3-datagram-04 was that we want to be able to assign unique handles to flow IDs in a generic way that is part of the this document. That would allow a general purpose implementation to be able to disambiguate lows without having to understand any specific extension.

During the MASQUE interim, there was a suggestion for a different design that would define a `name` parameter eg. `44; name=ecn-ect0`.

**Comment by tfpauly** [comment]
Specific extensions may also want to add more parameters.

What's the direct benefit of having a name, if I don't know what it means? Is it just to tell that flows are different?

**Comment by LPardue** [comment]
> Specific extensions may also want to add more parameters.

Right. The intention wasn't to *only* permit names. Other parameters can be sent since af-list allows that. The spec and/or interim meeting meeting slides might not have made that clear. In other words the goal was to allowing naming while avoiding an endpoint ignoring an unknown parameter and mishandling it as a name or some other extension. As the interim discussion evolved, it became clear there are other ways to specify the header that could achieve the goal.

I'm also realising my understanding of the extensibility requirements might not be fully representative - so don't take my replies as absolutionist.

**Comment by martinthomson** [comment]
As we discussed, if you want the names to imply some sort of semantic, then that is what parameters are for.  The example @tfpauly gave is perfect: if you want this flow to be for ECT0-marked packets, then `ecn=ect0` is perfectly good.  The name thing was ambiguous and relied on ordering.

The ECN case might be bad for the purposes of extension handling.  You can process these flows without needing to know the meaning of the ECN markings.  However, there might be other cases where the parameter indicates a change in the datagram contents.  I think that there is an important distinction here between what endpoints do with this (that is, User Agent and Origin Server in HTTP parlance) and what an intermediary might do.

An intermediary forwards all flows and only remaps flow identifiers.  It doesn't need to understand the content of datagrams. Therefore, it can do that without knowing what the semantics are.

Endpoints will need to understand the semantics in order to make use of the data.  This is tricky, because it means that you might need to negotiate understanding.  If we are doing MASQUE and a client adds a flow that is marked `48; ip`, with the intention that the flow contains whole IP packets (let's say of any version), the thing that consumes this flow needs to understand that.  That means that some extensions require *end-to-end* negotiation before the marking can be used.  A server that handles this in a request can reject the request and thereby avoid getting datagrams it can't handle (or being required to generate datagrams it can't produce).  However, the same is not true for responses, so maybe there is a need for clients to indicate what they are able to support.

Worth a separate issue?

**Comment by DavidSchinazi** [comment]
This issue is no longer relevant now that we have merged #52, closing.
