### ISSUE TITLE
Ability to accept or reject registration of context IDs

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#43]
During the 2021-04 MASQUE Interim, we discussed having the ability to accept or reject registration of context IDs. An important motivation for this is the fact that context ID registrations take up memory (for example it could be a compression context which contains the data that is elided) and therefore we need to prevent endpoints from arbitrarily making their peer allocate memory. While we could flow control context ID registration, a much simpler solution would be to have a way for endpoints to close/shutdown a registration.

**Comment by LPardue** [comment]
IIUC there's an opposing view that the constraints can be negotiated apiori. Either statically (such as defining an extension which states that there can only be N contenxts of a given type) or dynamically using something like a HTTP header. Failure to meet these constraints could lead to an HTTP/3 stream or connection error rather than a flow rejection.

**Comment by DavidSchinazi** [comment]
@LPardue I've filed #44 to discuss whether to register/negotiate at request start or mid-stream.

**Comment by tfpauly** [comment]
I think that if there is the ability to register mid-stream (#44), we need the ability to close/de-register/reject mid-stream as well. If we don't have mid-stream changes, then no need to negotiate.

However, someone trying to register something needs to be able to know whether or not the thing they registered will be accepted.

**Comment by achernya** [comment]
I agree that notification of the registration status is particularly important if we allow mid-stream registration.
