### ISSUE TITLE
Pick mechanism to register context IDs (header vs message)

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#44]
During the 2021-04 MASQUE Interim, we discussed multiple options for registering context IDs. Without going into the specific of the encoding, there are two broad classes of solutions:

* "Header" design
  * Once-at-setup registration
  * This happens during the HTTP request/response
  * Simplest solution is to use an HTTP header such as `Datagram-Flow-Id` (encoding TBD)
  * Example use-case: CONNECT-UDP without extensions
* "Message" design
  * Mid-stream registration
  * This can happen at any point during the lifetime of the request stream
  * This would involve some sort of "register" message (encoding TBD, see separate issue)
  * Example use-case: CONNECT-IP on-the-fly compression (this can't be done at tunnel setup time because the bits top be compressed aren't always known at that time)
 
It's possible to implement once-at-setup registration using the Message design, but it isn't possible to implement mid-stream registration. Therefore I think we should go with the Message design. It would also be possible to implement both but I don't think that provides much value.

**Comment by LPardue** [comment]
I'd like to here some more from the WebTransport use case on the issue. 

My understanding is that the Requests are used to create WebTransport sessions and that creation of datagram flows could be a lot more ad-hoc / server generated than just the CONNECT-UDP case.

Cc @vvasiliev

**Comment by tfpauly** [comment]
Personally, I'd vote for either "message" or "message + header" (a la priorities), but not just "header". Mid-stream annotation of context/flow/etc is quite useful.

**Comment by ianswett** [comment]
I prefer "Message" only, since the dynamic use case seems like a fairly compelling use of sub-flows(contexts?).

I'm not sure there are many cases when one allocates all sub-flows up front AND needs to use a header to do that in a flexible way.  If an application needs multiple sub-flows, but they're fixed in number/format(ie: data and control), I don't think there's a need for a header or a "Message", since the application can consider that part of its internal format.
