### ISSUE TITLE
Is the context ID optional?

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#45]
This issue assumes that decide to go with the two-layer design described in #41. Given that design, some applications might not need the multiplexing provided by context IDs. We have multiple options here:

* Make context ID mandatory
  * Applications that don't need it waste a byte per datagram
* Negotiate the presence of context IDs using an HTTP header
  * Context IDs would still be mandatory to implement on servers because the client might send that header
* Have the method determine whether context IDs are present or not
  * This would prevent extensibility on those methods
* Create a REGISTER_NO_CONTEXT message
  * This assumes we use the Message design from #44
  * We add a register message that means that this stream does not use context IDs
  * This allows avoiding the byte overhead without sacrificing extensibility

**Comment by tfpauly** [comment]
Making the context ID mandatory is simple, although slightly wasteful.

For the variations where it is optional, I prefer the one that uses a header. It could work with a variant of #44 where we do Header + Message, and the Header determines whether or not you have contexts, and whether or not they can be dynamic.

**Comment by achernya** [comment]
What are the benefits of message over header to make it optional? To me it seems like header is sufficient, because the context IDs are end-to-end, and should not affect intermediaries, making the header a natural place to put it. I think having the context ID be the default behavior and the header is to opt-out is the right decision if we were to allow removing it.

**Comment by afrind** [comment]
>  I think having the context ID be the default behavior and the header is to opt-out is the right decision if we were to allow removing it.

This is a bit of a bike-shed, but why would it default to having context-IDs instead of not having them?

**Comment by ianswett** [comment]
I think the second option "Negotiate the presence of context IDs using an HTTP header" is the best personally.

In terms of: "Context IDs would still be mandatory to implement on servers because the client might send that header", I assume server in this context is the final application server, not a proxy?  Even so, I'd argue it's applications which decide if they need this functionality, so if a server only implemented one application and it didn't use Context-IDs, then I don't see why it would need to implement it.

**Comment by achernya** [comment]
Ian, in your comment, are you talking about an intermediary when you say "proxy"? If so, then an intermediary need not implement anything based on the payload of than H3 DATAGRAM, it only has to pass the data along. That may be worth a clarification.

**Comment by LPardue** [comment]
Having context ID optional has a nice future-proof property - other uses of datagrams in HTTP/3 can decide if they want the second layer or not. 

I wouldn't even state it as application needing multiplexing or not. Other applications might find it very useful to include a second ((third, fourth, fifth) layer of frame header. I think its fine for us to state as much in this in the spec, while also defining an explicit second layer for multiplexing.

**Comment by ianswett** [comment]
Yes, by proxy I meant intermediary.  And I agree about what intermediaries need to do, I just wanted to ensure I understood what server meant when David used it above.

Yup, whenever all this gets written up, we can make it clear that intermediaries can ignore much of this.

**Comment by vasilvv** [comment]
The method defines the semantics of datagrams for a particular request, thus I think the third option makes most sense. I don't see a point in using explicit negotiation, since in the two cases I can think of the top of the head, the answer is always clear from the method (CONNECT-IP seems to always want context IDs, WebTransport does not ever want context IDs).  If some method starts out without context, but wants to add context later, it can add its own negotiation.

**Comment by ianswett** [comment]
One set of use cases for which the method approach(3) is best are those where there are multiple context IDs but they're predefined by the method and don't need negotiation.  My strawman is WebRTC.
