### ISSUE TITLE
The spec should discuss how h3-datagram works(or does not) with priority

### ISSUE THREAD

**Issue by ianswett** [ietf-wg-masque/draft-ietf-masque-h3-datagram#46]
I think it's be valuable for h3-datagram to be able to use the new HTTP priority draft.

I think it'd be ok to say that the datagram flow has the same prioritization as the request that initiated it.  I don't think anything more complex is necessary, but I could be wrong.

**Comment by DavidSchinazi** [comment]
That seems reasonable to me, assuming that we can get some implementations of this first. I suspect that we'll want this text to live in whichever gets published last between draft-ietf-masque-h3-datagram and [draft-ietf-httpbis-priority](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-priority).

**Comment by LPardue** [comment]
The extensible priorities draft doesn't prioritise streams, it prioritizes responses. Is it sufficient that only a client can control the relative priority of datagrams coming back to it?

**Comment by LPardue** [comment]
oh and FWIW as an editor on priorities, we are pretty close to a WGLC. If there's merit in saying something about datagrams and priorities, putting it here feels like the right thing.

**Comment by ianswett** [comment]
> The extensible priorities draft doesn't prioritise streams, it prioritizes responses. Is it sufficient that only a client can control the relative priority of datagrams coming back to it?

Given the client already has the ability to control the relative priority of datagrams its sending, I think that's ok?

Possibly there are use cases where the server wants to indicate a priority to the client as well?

My strawman use case is tunneling multiple HTTP/3 connections: One goes to the origin, one goes to a static content server, ads, etc, and the client wants to receive data from the origin at a higher priority than the other data.

**Comment by LPardue** [comment]
I think that is a good use case! I don't know if someone will turn around and say they really want to support that server control use case, I'm keen to hear strong proponents to really understand why.

Making DATAGRAM priority based on streams aids parity between CONNECT and CONNECT-UDP cases. 

To your mind, would datagrams be prioritized against other datagrams and other streams? There's probably something to say here, especially the edge case where there is data to be sent non-incrementally on the stream AND the datagram flow.

Something to consider is also that if we go ahead with a 2-layer approach, whether we want to expose per-flow priorities. Maybe that can be done by carrying the extensible priority value as an extension field in the flow creation message. Although it does sound a bit too much complexity.

**Comment by ianswett** [comment]
> To your mind, would datagrams be prioritized against other datagrams and other streams? There's probably something to say here, especially the edge case where there is data to be sent non-incrementally on the stream AND the datagram flow.
>

Yes, I would expect all datagrams and streams to be prioritized together.  If there's a response and it has associated datagrams, I'm not sure which would get precedence over one another, but if the assumption is that the response will be small, it probably makes sense to prioritize that?

> Something to consider is also that if we go ahead with a 2-layer approach, whether we want to expose per-flow priorities. Maybe that can be done by carrying the extensible priority value as an extension field in the flow creation message. Although it does sound a bit too much complexity.

I really hope we can avoid that, since it means the proxy/intermediary would have to deal with subflows, whereas currently it doesn't have to.  Also, for most of the subflow use cases I've heard, I don't think that would be valuable or necessary.

**Comment by LPardue** [comment]
Agree about the context/subflows things. Lets avoid that.

For the bigger picture stuff I'd need to think on this some more. Perhaps a mildly flexible solution is to define an extensible priorities extension that would 

1) explain some of the considerations into scheduling relative priorities between streams and datagrams

2) define a `dgram` parameter to allow explicit setting of datagram flow priority.  For example, to have an incremental stream at urgency 1 and incremental datagram at urgency 3

```
priority: u=1, i, dgram;u=3;i
```

We could then state that omitting the `drgram` parameter means the stream's priority is used.

3) by adding more params to `dgram` we could even support explicit signalling of the wish for shared priority space, or segregated.

**Comment by DavidSchinazi** [comment]
I'd say that defining a new `dgram` prioritization parameter should be left to its own document, I'd prefer not to have this in h3-datagram itself

**Comment by LPardue** [comment]
I agree its scope creep. I would be ok with this document saying very little and punting the problem to a `draft-ietf-httpbis-dgram-priorities` (which I would entertain co-writing)

**Comment by afrind** [comment]
I think defining priorities of sub-flows would be useful in Ian's use case if you wanted to merge the priorities of streams within the tunneled QUIC connections at the entry proxy, rather that strictly prioritize one tunnel over another.

One could do this by registering a context-ID for each priority level.  This context-ID could be used by the intermediary (did I break the rules again?) to determine the priority of the datagram back towards the client.

**Comment by DavidSchinazi** [comment]
I'm going to propose closing this issue with no action, with the intent to leave this functionality to extensions.

**Comment by afrind** [comment]
Adding text that says by default datagrams inherit the priority of the stream they are associated with seems likely to capture the most common cases.  If we can't agree on that and want to punt, it would be good to indicate in the draft that priority of datagrams is undefined/implementation specific.

**Comment by LPardue** [comment]
I'll would be happy with Alan's suggestion. I will prepare a PR unless someone beats me too it.

**Comment by DavidSchinazi** [comment]
@LPardue stating that it is undefined sounds great to me.

**Comment by ianswett** [comment]
I prefer it inherit the priority of the associated stream as @afrind suggested.

**Comment by ianswett** [comment]
If I'm an intermediary l7 load balancer, and support h3-datagram but am not looking deeper into the payload, I'm going to have to make scheduling decisions, so leaving it undefined could cause large differences in how h3-datagram based applications work on different intermediaries.

**Comment by LPardue** [comment]
Right but that's the situation the base HTTP/3 specification has right now too. 

And even if the L7 balancer applies scheduling logic based on the extensible priorities draft, 

1) it would need to decide how to schedule ingress data (request content) itself, since that is not defined 
2) we have little experience about how to schedule datagram and stream data concurrently. I would expect implementers to turn around immediately and ask us how to do that if we say explicitly here that there is a datagram priority signal.

I am not saying we punt the question indefinately. But in the interest of making progress here (especially to limit feature creep) I am suggesting we write a standalone `draft-pardue-masque-h3-dgram-priorities` document that can capture all the concerns as completely as is useful. If that draft makes rapid progress it might be a candidate for getting incorporated back into the H3 datagram specification. I would be happy to bootstrap that document in a new repo and work with Alan, Ian or other folks that can give some opinions.

**Comment by DavidSchinazi** [comment]
+1 to @LPardue. The more I think about this the more I believe that H3DGRAM has to match what H3 does - in a vacuum as an implementor I don't know how to implement "datagram should inherit priority of the corresponding stream" when no one has actually defined what a priority is. There are important questions like "should higher priority completely starve lower priority or not?" that are not answered by H3. H3DGRAM itself cannot depend on a given priorities extension, because we might define a different priorities scheme later. Having a separate draft that explains how to combine draft-ietf-masque-h3-datagram and draft-ietf-httpbis-priority sounds like the best option.
