### ISSUE TITLE
Do context ID closures need more details?

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-h3-datagram#53]
In #52, we introduce the CLOSE_DATAGRAM_CONTEXT capsule which allows endpoints to close a context. That message currently only contains the context ID to close. @bemasc suggests that we may want to add more information there.
* Should we differentiate between "context close" and "context registration rejected"?
* Should we add an error code?

In particular, do folks have use cases for these features?

**Comment by bemasc** [comment]
My first concern is with infinite loops.  If the context was "garbage collected" by the recipient, the sender can simply re-create it if they still want it.  However, if it was closed due to incompatibility (i.e. rejected) or hitting a resource limit (e.g. max # of contexts), reopening it in response will produce a tight infinite loop.

This could be maybe be avoided by some kind of heuristic, but an explicit indication of what's going on seems better.
