### ISSUE TITLE
MTU handling

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-h3-datagram#65]
This has been sent to the MASQUE WG mailing list in hopes to get some discussion there. However, I want an issue that tracks this: 

In the work of writing up our Connect-IP proposal (https://datatracker.ietf.org/doc/draft-kuehlewind-masque-connect-ip/) we looked into how to deal with MTU issues effectively. Our conclusion was that this is going to be a general problem for any user of HTTP Datagrams. Thus, we like to propose that MTU handling is done within HTTP datagram. 

This email will start explaining what we see as requirements for a MTU signaling solution for HTTP datagram, then propose a potential solution. 

Lets start with a figure that provides us with a framework to discuss the requirements:

```
+--------+ Path#1A +--------+        +-------+        +--------+
|Client A|<------->| HTTP   | Path#2 | MASQUE| Path#3 |        |
+--------+         | Inter- |<------>| Server|<------>| Target |
+--------+ Path#1B | mediary|        |(proxy)|        |        |
|Client B|<------->|        |        |       |        |        |
+--------+         +--------+        +-------+        +--------+
```

I think what makes this a bit more complex is the fact that we need to consider HTTP intermediaries, such as a front end load balancer that terminates a first QUIC and HTTP/3 connection between the client and that intermediary. From that intermediary another HTTP connection is used towards the HTTP server that consumes and produces the HTTP datagrams, and in the case of CONNECT-UDP and CONNECT-IP it also have a third path towards the target to consider. This figure includes two clients to remind us to consider that the HTTP intermediary may actually aggregate the HTTP request and response and HTTP datagram over one HTTP/2 or HTTP/3 connection over Path #2. In the case of MTU this complicates things more as the proxy cant assume that all HTTP requests have the same MTU for its datagrams on a HTTP/3 connection. And the Intermediary will be the entity that have direct knowledge of the client facing as well as the next hop MTU over the HTTP connections that may all differ in MTU. 

We also have to consider the fact that the underlying transport connection may at any time be subject to a IP MTU change due to route change for the path between the nodes. In addition if one have enabled PMTUD in TCP or QUIC a larger MTU on the individual path could be made available and in some case desirable to use. Thus, we need to consider dynamic changes during the HTTP connections life time and each HTTP request response pairs usage of HTTP datagram. 

So when using HTTP/3 datagram there are a strict MTU limit on the individual datagrams for it to be possible to be sent as QUIC datagrams, and not being forced to be encapsulated as CAPSULES over the reliable stream. This is clearly a possibility but results in that the datagrams are sent reliable and in order for each HTTP request, i.e. Connect-UDP or CONNECT-IP request. Also in case some end-to-end payloads fit in HTTP datagrams and others don’t there is potential for reordering among the payloads. Thus, to avoid this the client and the proxy needs to determine what the lowest currently supported HTTP datagram size on the path. 

For each QUIC connection the end point will know what the initial MTU value is for this path when the HTTP/3 connection has been successful completed. However, that knowledge will not be available if one attempt to construct and send the HTTP request prior to connection establishment has concluded.

So the requirements we see for an MTU handling solution for HTTP Datagrams are the following.

1)	Hop-by-hop signaling across the HTTP entities of the lowest MTU of any sub-path
2)	Needs to be associated to a particular HTTP request or end-to-end path to support aggregation by HTTP intermediaries
3)	Endpoints needs to be able to initiate update of the MTU value upon detection of any changes during HTTP Datagram streams lifetime.
4)	HTTP Intermediaries needs to be able to initiate updates of the MTU value upon detecting MTU changes from the individual HTTP connections.

Solution proposal
==============

A new HTTP Datagram Capsule is defined for MTU value exchange. This one is intended for the HTTP intermediary that needs to interpret, update or initiate sending of it. Thus, it needs to be a fixed registered type so it can be easily processed. It can also be exchanged in parallel to the Register_Datagram_* capsules as at that point the underlying HTTP connection is established and initial HTTP Datagram values will be known. A capsule will also travel all the way to the end. And an intermediary can initiate one in each direction for request paths. The only downside I see of this is that one is required per open stream when MTU changes occurs. Maybe someone have an idea of how to handle signaling when aggregating multiple endpoints streams onto one HTTP/3 connection. 

To make it more efficient, rather than sending one MTU capsule per stream, an MTU capsule could list all streams it is applicable to. That way the number of MTU capsules would be no more than the number of end-to-end paths actually used.

**Comment by DavidSchinazi** [comment]
Hi @gloinul thanks for proposing this work item. From reading your problem statement and proposal, this will require non-trivial amounts of complexity. Resolving that will take time. I don't see a reason to delay the HTTP Datagrams draft because of this, so I'd suggest building this as an extension to HTTP Datagrams. I think this would even be a great way to test out our new extensibility mechanism! Can you write this up as a separate draft please?

**Comment by gloinul** [comment]
Yes, it is non-trivial. However, I think we need to settle if we have a day one need for this mechanism to ensure that CONNECT-UDP actually can work properly and handle QUIC in QUIC when the outer tunnel uses minimal QUIC packets. Similarly we have a need for CONNECT-IP to handle IPv6 minimal packet size. So I think we need to discuss if this needs to be solved.

But, yes I am willing to write this up in spec form, but I was more thinking of a PR to the HTTP-DATAGRAM draft.

**Comment by DavidSchinazi** [comment]
I don't see a day one need here that isn't addressed by [Ben's proposal](https://mailarchive.ietf.org/arch/msg/masque/7KJiS6bznHSlCqz1q8HTXoAk0to/). Given the current text, CONNECT-UDP (and -IP) endpoints can detect datagram blackholing and switch to capsules.

**Comment by gloinul** [comment]
I don't understand the following statement "CONNECT-UDP (and -IP) endpoints can detect datagram blackholing and switch to capsules." I don't believe that is true in scenarios with HTTP Intermediaries as the MASQUE endpoint in those case lacks visibility of the dropping of the HTTP Datagram, unless additional signals are added. But, I would also prefer that we discuss this on the mailing list. I just think closing the issue was premature.

**Comment by DavidSchinazi** [comment]
You don't need an explicit signal to know that a packet was dropped, you can infer that through lack of acknowledgements. Since there aren't acknowledgements at the datagram layer itself, you'd need to partner with the transport protocol running over CONNECT-UDP or CONNECT-IP to get that signal. That isn't trivial, but if we transparently solve this at the datagram layer (let's say we add a "datagram too big" capsule and then have the datagram layer use it to switch to reliable capsules for example) then you'd end up with terrible performance because in most scenarios you'd be much better off with the higher level transport protocol using a smaller MSS that fits in datagrams. So all this to say: this isn't an easy problem to solve, and having an explicit signal isn't a silver bullet that solves it easily. Since we need to involve the higher layers, then we have many options to pick from, and not all of them require an explicit signal.

**Comment by gloinul** [comment]
Agree that for sufficiently large MTU you want the end-to-end PMTUD to work and dropping will be necessary. However, we are going to have requirements on minimal packet sizes, that is where we end up in needing a signal. In addition if the tunnel HTTP Datagram ingress knows the MTU, then for the MASQUE use cases it can send back the appropriate signal towards an remote IP point or through the API to the application using MASQUE. If an HTTP intermediary simply drop packets that are to large and send no signal back. Then the HTTP datagram ingress has no knowledge and no type of signal intended to speed up PMTUD is also sent. Which, makes results us from potentially breaking the IPv6 specification requirements in two ways when using it for CONNECT-IP. 

First we may not support the required datagram size of 1280 bytes.
Secondly, we are not supporting the IPv6 PMTUD model of actually sending ICMPv6 PTBs. Yes, this may not work as well as it should, but it is still required functionality.

**Comment by DavidSchinazi** [comment]
Summarizing the [list discussion](https://mailarchive.ietf.org/arch/msg/masque/_fiWFDqS4UDKECR_cQW4bswhUkY/) we had on this topic, both WebTransport and CONNECT-UDP are working well in production without an MTU solution at the HTTP Datagrams layer. There is also no proposal for an MTU solution that works for all possible use cases of HTTP Datagrams.

The only unsolved problem here is how to reconcile a low HTTP Datagram MTU with the IPv6 minimum link MTU. Since that's specific to CONNECT-IP, I've filed a specific issue for that there: https://github.com/ietf-wg-masque/draft-ietf-masque-connect-ip/issues/45.

Based on this, I'm going to close this issue with no action. If you disagree, please reopen/comment.
