### ISSUE TITLE
Merge REGISTER_DATAGRAM_CONTEXT and REGISTER_DATAGRAM_NO_CONTEXT capsules

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-masque/draft-ietf-masque-h3-datagram#68]
There are two possible ways to encode REGISTER_DATAGRAM capsule: using two different capsules (current variant), or using a single capsule with a field indicating whether the context is present.  While those two are largely isomorphic, I feel like the latter would help us avoid situations where libraries or intermediaries only support one but not the other.

**Comment by LPardue** [comment]
To address one I had the expectation that the capsule types would be base level and all implementations would support them. Maybe we have different expectations. 

To address the more technical point, what would a merged capsule look like? In H3, we don't have a flags section for frames to signals similar but unique variants. The HTTP/3 PRIORITY_UPDATE frame in Extensible Priorities started by encoding optionality as a 1 byte field in the frame. Due to feed back we switched to using different frame code points, a bit like how QUIC DATAGRAMS also work. Since we already have two frame code points it doesn't seem like we are too far off how other parts of the stack already do things.

**Comment by MikeBishop** [comment]
Yes, it's entirely equivalent to say there's a one-bit flag in the capsule type indicating whether (0x0) the Context ID is absent and the stream will not use Context IDs, or (0x01) the Context ID field is present.  I don't feel like there needs to be a wire format difference here, and how we spell it in the draft is purely editorial.
