### ISSUE TITLE
Remove context identifiers

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-masque/draft-ietf-masque-h3-datagram#84]
The capsules that signal use of different datagram contexts (or the absence thereof) assume that there is a generic need for this form of identification.  That has not been established.  WebTransport certainly doesn't need it.  

As this is an *end-to-end* signal anyway, it is also a *protocol-specific* signal.  All uses of this framework are perfectly capable of doing their own signaling and negotiation.  A one-size-fits-all mechanism is more likely a one-size-fits-few mechanism, but it still comes with costs that every user has to bear (see ietf-wg-webtrans/draft-ietf-webtrans-http3#54 for instance).

For instance, if CONNECT-UDP wanted to signal ECN and DSCP, that might be more efficiently achieved with a single byte (2 + 6) rather than a varint.  If CONNECT-IP wanted different compression contexts, that might be suited to a varint, but why would this draft be in a position to decide that?

As there is no value in an intermediary looking at these context identifiers - I would argue negative utility in the RFC 8558 sense - these should be removed from the protocol.

The only potential value I see in having some sort of signaling here is to explicitly signal the use of DATAGRAM frames associated with a stream.  However, as we have agreed to send DATAGRAM frames without negotiation, that too seems like it won't be needed.

**Comment by DavidSchinazi** [comment]
Deciding where to draw the line between having a feature live in the shared domain or an application-specific domain is always tricky. On one hand if you share every feature, each application has to do useless work. On the other if you don't share you end up reinventing many similar yet different wheels. In this case it isn't obvious because we have two applications that need it and one that doesn't. So we can't make a decision based on architectural fundamentals.

The question here is therefore a pragmatic one: how do we trade off between WebTransport's ease of implementation and CONNECT-IP's extensibility? For me, it comes down to negotiation. I proposed the design that's currently in the drafts because it has one property I really like: zero-round-trip negotiation. In other words, the client is free to choose between using or not using contexts, and can immediately start sending using its preferred choice without waiting to see the server's headers. I see it as the best of both worlds: WebTransport gets efficient wire encoding at a very small added implementation cost, and CONNECT-IP gets an efficient compression mechanism.

**Comment by vasilvv** [comment]
I'm not sure why this is presented as a dichotomy.  The draft can provide a mechanism for contexts layered on top of a common capsule framing, and then CONNECT-IP can use both, while WebTransport can use datagrams+capsules directly (the exact semantics depending on the specific method or `:protocol` value used).

**Comment by DavidSchinazi** [comment]
@vasilvv my concern there is that if WebTransport decides to only use a subset of HTTP Datagrams, then when someone implements a WebTransport-compatible intermediary, they're going to skip implementing contexts. If we decide that all applications can use contexts, it will ensure we have a healthy ecosystem of intermediaries that support any HTTP Datagram application.

**Comment by vasilvv** [comment]
Sure, just like they can decide to drop any request that has method `CONNECT-UDP`, or whatever `:protocol` value you come up with.  There will be inevitable friction to introducing any specific new use of datagrams, and I don't think you can pay the entirety of that cost upfront.  The intermediaries that are used by people who want to pass MASQUE traffic will implement contexts, and for the rest, this doesn't really matter.

**Comment by DavidSchinazi** [comment]
There's a very big difference here: if we decide that all HTTP Datagram applications are the same to intermediaries, it takes less work for them to support all of them than it does to support only one. That's what ensures that they all get supported. The risk is someone implementing half the protocol to save time, not someone going out of their way to disallow some options.

**Comment by vasilvv** [comment]
I'm confused.  How do you make them same to the intermediaries while making them different to the endpoints?

**Comment by DavidSchinazi** [comment]
By ensuring that intermediaries treat all opaque capsules the same, but having endpoints parse and react to each capsule according to its semantics.

**Comment by vasilvv** [comment]
But if the intermediaries treat all of the capsules the same, it doesn't matter if datagram contexts are optional or not, since it would require parsing capsules to know that.

**Comment by LPardue** [comment]
Related to this, we have

> Implementations of HTTP Datagrams MUST provide a context ID allocation service. That service will allow applications co-located with HTTP to request a unique context ID that they can subsequently use for their own purposes.

This seems to be a bit of a backdoor requirement. An implementation that only cared to support no-context datagrams would not need the context ID allocation service.
