### ISSUE TITLE
Consider a GENERAL_ERROR close code

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-h3-datagram#95]
There may be cases (imagine new capsule types) where somthing went wrong but none of the existing codes are appropriate. Signalling NO_ERROR is not appropriate and may be misleading.

**Comment by DavidSchinazi** [comment]
Close context capsules carry two items of information about the reason for closing: close codes and close details. In my mind, the close code is meant for software (if you receive this close code instead of that one, the implementation will behave differently) whereas the close details are for humans trying to debug things. So when we're thinking of adding a new close code (as opposed to sending more prose in close details), it begs the question: how would software treat GENERAL_ERROR differently from NO_ERROR?

**Comment by LPardue** [comment]
good question!

We should probably try to capture the ethos of these error codes so everyone has the same expectation. For instance HTTP/3 says

> Stream errors are distinct
   from HTTP status codes which indicate error conditions.  Stream
   errors indicate that the sender did not transfer or consume the full
   request or response, while HTTP status codes indicate the result of a
   request that was successfully received.

Is a close code more like a HTTP status code or a stream error code? It feels like the latter, so to use your examples, when thinking about retry registration, it sounds like we have categories where it is safe to retry registration (NO_ERROR), most definitely not allowed to retry (UNKNOWN_FORMAT, DENIED), maybe retry (RESOURCE_LIMIT). So I guess a GENERAL_ERROR type would fit into a maybe retry bucket. And if some new use of capsules requires "don't retry" where the existing codes aren't suited, they really should define a new code.

Alternatively, we seem to just be reinventing HTTP status codes - so we could, y'know, just use that value range here :laughing:

**Comment by DavidSchinazi** [comment]
I agree writing some text about the ethos and intended use of closes codes is a good idea. Perhaps something like:
* Close codes are intended to allow implementations to react differently when they receive them - for example, some close codes require the receiver to not open another context under certain conditions. Extensions to this mechanism MAY define new close codes if they wish to have receivers react differently.

I don't think NO_ERROR is in the "safe to retry" category, because unknown codes are meant to be treated as NO_ERROR. Perhaps we merge NO_ERROR and GENERAL_ERROR and rename the result UNKNOWN_ERROR?

**Comment by LPardue** [comment]
How about we spin off "ethos and intention" to a new ticket?

> I don't think NO_ERROR is in the "safe to retry" category, because unknown codes are meant to be treated as NO_ERROR. 

Ah good point. 

I'm all for bikeshedding a name - how about MAYBE_ERROR?

I realise that the current definition

> NO_ERROR: This indicates that the registration was closed without any additional information.

is slightly ambiguous as to whether the `Close Details" field would be populated or not.

**Comment by DavidSchinazi** [comment]
> How about we spin off "ethos and intention" to a new ticket?

Sure!

> I'm all for bikeshedding a name - how about MAYBE_ERROR?

I prefer UNKNOWN_ERROR to MAYBE_ERROR, but I don't care too much.

> I realise that the current definition
> 
> > NO_ERROR: This indicates that the registration was closed without any additional information.
> 
> is slightly ambiguous as to whether the `Close Details" field would be populated or not.

Agreed. Perhaps something like:
* NO_ERROR: This indicates that the registration was closed without any action specified for the receiver.

I'm not loving that sentence, but my intent was to convey that close codes exist to carry some action or requirement of the receiver, and NO_ERROR carries no such action or requirement.
